apiVersion: base.scone.cloud/v1beta1
kind: SGXPlugin
metadata:
  name: sgxplugin
spec:
  autoUpdate: true
  imagePullSecrets:
   - name: sconeapps
---

apiVersion: base.scone.cloud/v1beta1
kind: LAS
metadata:
  name: las
spec:
  image: "registry.scontain.com/scone.cloud/las:no-epid-production"
  imagePullSecrets:
   - name: sconeapps

---

apiVersion: services.scone.cloud/v1beta1
kind: CAS
metadata:
  name: cas-no-backup
spec:
  image: registry.scontain.com/scone.cloud/cas
  imagePullSecrets:
    - name: sconeapps
  service:
    type: NodePort
  imagePullPolicy: Always
  persistence:
    enabled: true
  podAnnotations:
    scone-operator/inject-pull-secret: "true"
