apiVersion: v1
kind: Namespace
metadata:
  name: scone-system
  labels:
    name: scone-system
  annotations:
    scone-operator/inject-pull-secret:  "true"
    sconeapps/inject-pull-secret:  "true"

---

apiVersion: base.scone.cloud/v1beta1
kind: SGXPlugin
metadata:
  name: sgxplugin
spec:
  autoUpdate: true
  imagePullSecrets:
   - name: scone-operator-pull

---

apiVersion: base.scone.cloud/v1beta1
kind: LAS
metadata:
  name: las
spec:
  image: "registry.scontain.com/scone.cloud/las:no-epid-production"
  imagePullSecrets:
   - name: scone-operator-pull
