apiVersion: base.scone.cloud/v1beta1
kind: SGXPlugin
metadata:
  name: sgxplugin
spec:
  autoUpdate: true
  imagePullSecrets:
   - name: sconeapps
---

apiVersion: base.scone.cloud/v1beta1
kind: LAS
metadata:
  name: las
spec:
  image: "registry.scontain.com/scone.cloud/las:no-epid-production"
  imagePullSecrets:
   - name: sconeapps

---

apiVersion: services.scone.cloud/v1beta1
kind: CAS
metadata:
  name: cas
spec:
  image: registry.scontain.com/scone.cloud/cas
  imagePullSecrets:
    - name: sconeapps
  service:
    type: NodePort
  imagePullPolicy: Always
  persistence:
    enabled: true
  backup-controller:
    enabled: true
    session: "cas-backup-controller-policy-name/register"
  databaseSnapshots:
    enabled: true
    persistence:
      enabled: true
