# Substitution:
#
# - $NAME is replaced by the NAME of the release
# - $POLICY_NAME is replaced by the policy name
#
apiVersion: services.scone.cloud/v1beta1
kind: CAS
metadata:
  name: "$NAME"  
  namespace: $ns
spec:
  image: registry.scontain.com/scone.cloud/cas
  imagePullSecrets:
    - name: sconeapps
  service:
    type: NodePort
  imagePullPolicy: Always
  persistence:
    enabled: true
  backup-controller:
    enabled: true
    session: $POLICY_NAME/register
    image: "registry.scontain.com/scone.cloud/backup-controller"
  livenessProbe:
    enabled: true
#    failureThreshold: 5
#    periodSeconds: 60
#    timeoutSeconds: 60
#    initialDelaySeconds: 30
  startupProbe:
     enabled: true
#    failureThreshold: 5
#    periodSeconds: 60
#    timeoutSeconds: 60
#    initialDelaySeconds: 30
  attestedCLIProbes: true
  databaseSnapshots:
    enabled: true
    persistence:
      enabled: true
  networkPolicy:
    enabled: true
