apiVersion: v1
kind: Namespace
metadata:
  name: scone-system
  labels:
    name: scone-system
  annotations:
    scone-operator/inject-pull-secret:  "true"
    sconeapps/inject-pull-secret:  "true"

---

apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: scone-system
  annotations:
    scone-operator/inject-pull-secret:  "true"
    sconeapps/inject-pull-secret:  "true"
