apiVersion: services.scone.cloud/v1beta1
kind: CAS
metadata:
  name: mycas
spec:
  image: registry.scontain.com/scone.cloud/cas
  imagePullSecrets:
    - name: sconeapps
  service:
    type: NodePort
  imagePullPolicy: Always
  persistence:
    enabled: true
  backup-controller:
    enabled: true
    session: mycas-backup-controller/register
